import { MEDIA_AUDIO_FIELD_LABELS } from "./media-audio-field-metadata.js";
import { IRC_FIELD_LABELS } from "./schema.irc.js";

export const FIELD_LABELS: Record<string, string> = {
  meta: "Metadata",
  "meta.lastTouchedVersion": "配置最后修改版本",
  "meta.lastTouchedAt": "配置最后修改时间",
  env: "Environment",
  "env.shellEnv": "Shell 环境导入",
  "env.shellEnv.enabled": "Shell 环境导入启用",
  "env.shellEnv.timeoutMs": "Shell 环境导入超时 (ms)",
  "env.vars": "环境变量覆盖",
  wizard: "Setup Wizard State",
  "wizard.lastRunAt": "向导最后运行时间",
  "wizard.lastRunVersion": "向导最后运行版本",
  "wizard.lastRunCommit": "向导最后运行提交",
  "wizard.lastRunCommand": "向导最后运行命令",
  "wizard.lastRunMode": "向导最后运行模式",
  diagnostics: "Diagnostics",
  "diagnostics.otel": "OpenTelemetry",
  "diagnostics.cacheTrace": "缓存跟踪",
  logging: "Logging",
  "logging.level": "日志级别",
  "logging.file": "日志文件路径",
  "logging.consoleLevel": "控制台日志级别",
  "logging.consoleStyle": "控制台日志样式",
  "logging.redactSensitive": "敏感数据脱敏模式",
  "logging.redactPatterns": "自定义脱敏模式",
  cli: "CLI",
  "cli.banner": "CLI 横幅",
  "cli.banner.taglineMode": "CLI 横幅标语模式",
  update: "Updates",
  "update.channel": "更新通道",
  "update.checkOnStart": "启动时检查更新",
  "update.auto.enabled": "自动更新启用",
  "update.auto.stableDelayHours": "自动更新稳定延迟 (小时)",
  "update.auto.stableJitterHours": "自动更新稳定抖动 (小时)",
  "update.auto.betaCheckIntervalHours": "自动更新 Beta 检查间隔 (小时)",
  "diagnostics.enabled": "诊断启用",
  "diagnostics.flags": "诊断标志",
  "diagnostics.stuckSessionWarnMs": "卡住会话警告阈值 (ms)",
  "diagnostics.otel.enabled": "OpenTelemetry 启用",
  "diagnostics.otel.endpoint": "OpenTelemetry 端点",
  "diagnostics.otel.protocol": "OpenTelemetry 协议",
  "diagnostics.otel.headers": "OpenTelemetry 头部",
  "diagnostics.otel.serviceName": "OpenTelemetry 服务名",
  "diagnostics.otel.traces": "OpenTelemetry 跟踪启用",
  "diagnostics.otel.metrics": "OpenTelemetry 指标启用",
  "diagnostics.otel.logs": "OpenTelemetry 日志启用",
  "diagnostics.otel.sampleRate": "OpenTelemetry 跟踪采样率",
  "diagnostics.otel.flushIntervalMs": "OpenTelemetry 刷新间隔 (ms)",
  "diagnostics.cacheTrace.enabled": "缓存跟踪启用",
  "diagnostics.cacheTrace.filePath": "缓存跟踪文件路径",
  "diagnostics.cacheTrace.includeMessages": "缓存跟踪包含消息",
  "diagnostics.cacheTrace.includePrompt": "缓存跟踪包含提示",
  "diagnostics.cacheTrace.includeSystem": "缓存跟踪包含系统",
  "agents.list.*.identity.avatar": "身份头像",
  "agents.list.*.skills": "代理技能过滤",
  "agents.list[].runtime": "代理运行时",
  "agents.list[].runtime.type": "代理运行时类型",
  "agents.list[].runtime.acp": "代理 ACP 运行时",
  "agents.list[].runtime.acp.agent": "代理 ACP 管理代理",
  "agents.list[].runtime.acp.backend": "代理 ACP 后端",
  "agents.list[].runtime.acp.mode": "代理 ACP 模式",
  "agents.list[].runtime.acp.cwd": "代理 ACP 工作目录",
  agents: "Agents",
  "agents.defaults": "代理默认设置",
  "agents.list": "代理列表",
  gateway: "Gateway",
  "gateway.port": "网关端口",
  "gateway.mode": "网关模式",
  "gateway.bind": "网关绑定模式",
  "gateway.customBindHost": "网关自定义绑定主机",
  "gateway.controlUi": "控制面板",
  "gateway.controlUi.enabled": "控制面板启用",
  "gateway.auth": "网关认证",
  "gateway.auth.mode": "网关认证模式",
  "gateway.auth.allowTailscale": "网关认证允许 Tailscale 身份",
  "gateway.auth.rateLimit": "网关认证速率限制",
  "gateway.auth.trustedProxy": "网关可信代理认证",
  "gateway.trustedProxies": "网关可信代理 CIDR",
  "gateway.allowRealIpFallback": "网关允许 x-real-ip 回退",
  "gateway.tools": "网关工具暴露策略",
  "gateway.tools.allow": "网关工具允许列表",
  "gateway.tools.deny": "网关工具拒绝列表",
  "gateway.channelHealthCheckMinutes": "网关通道健康检查间隔 (分钟)",
  "gateway.channelStaleEventThresholdMinutes": "Gateway Channel Stale Event Threshold (min)",
  "gateway.channelMaxRestartsPerHour": "Gateway Channel Max Restarts Per Hour",
  "gateway.tailscale": "网关 Tailscale",
  "gateway.tailscale.mode": "网关 Tailscale 模式",
  "gateway.tailscale.resetOnExit": "网关 Tailscale 退出时重置",
  "gateway.remote": "远程网关",
  "gateway.remote.transport": "远程网关传输方式",
  "gateway.reload": "配置重载",
  "gateway.tls": "网关 TLS",
  "gateway.tls.enabled": "网关 TLS 启用",
  "gateway.tls.autoGenerate": "网关 TLS 自动生成证书",
  "gateway.tls.certPath": "网关 TLS 证书路径",
  "gateway.tls.keyPath": "网关 TLS 密钥路径",
  "gateway.tls.caPath": "网关 TLS CA 路径",
  "gateway.http": "网关 HTTP API",
  "gateway.http.endpoints": "网关 HTTP 端点",
  "gateway.http.securityHeaders": "网关 HTTP 安全头",
  "gateway.http.securityHeaders.strictTransportSecurity": "严格传输安全 Header",
  "gateway.remote.url": "远程网关 URL",
  "gateway.remote.sshTarget": "远程网关 SSH 目标",
  "gateway.remote.sshIdentity": "远程网关 SSH 身份",
  "gateway.remote.token": "远程网关 令牌",
  "gateway.remote.password": "远程网关 密码",
  "gateway.remote.tlsFingerprint": "远程网关 TLS 指纹",
  "gateway.auth.token": "网关 令牌",
  "gateway.auth.password": "网关 密码",
  browser: "Browser",
  "browser.enabled": "浏览器启用",
  "browser.cdpUrl": "浏览器 CDP URL",
  "browser.color": "浏览器 强调 颜色",
  "browser.executablePath": "浏览器 可执行文件 路径",
  "browser.headless": "浏览器 无头 模式",
  "browser.noSandbox": "浏览器 无沙箱 模式",
  "browser.attachOnly": "浏览器 仅附加 模式",
  "browser.cdpPortRangeStart": "浏览器 CDP 端口 范围 启动",
  "browser.defaultProfile": "浏览器 默认 配置文件",
  "browser.profiles": "浏览器 配置文件",
  "browser.profiles.*.cdpPort": "浏览器 配置文件 CDP 端口",
  "browser.profiles.*.cdpUrl": "浏览器 配置文件 CDP URL",
  "browser.profiles.*.driver": "浏览器 配置文件 驱动",
  "browser.profiles.*.attachOnly": "浏览器 配置文件 仅附加 模式",
  "browser.profiles.*.color": "浏览器 配置文件 强调 颜色",
  tools: "Tools",
  "tools.allow": "工具 允许列表",
  "tools.deny": "工具 拒绝列表",
  "tools.web": "网页工具",
  "tools.exec": "执行工具",
  "tools.media.image.enabled": "启用 图片理解",
  "tools.media.image.maxBytes": "图片理解 最大 Bytes",
  "tools.media.image.maxChars": "图片理解 最大 Chars",
  "tools.media.image.prompt": "图片理解 提示",
  "tools.media.image.timeoutSeconds": "图片理解 超时 (秒)",
  "tools.media.image.attachments": "图片理解 附件 策略",
  "tools.media.image.models": "图片理解 模型",
  "tools.media.image.scope": "图片理解 范围",
  "tools.media.models": "媒体 Understanding Shared 模型",
  "tools.media.concurrency": "媒体 Understanding 并发",
  ...MEDIA_AUDIO_FIELD_LABELS,
  "tools.media.video.enabled": "启用 Video Understanding",
  "tools.media.video.maxBytes": "Video Understanding 最大 Bytes",
  "tools.media.video.maxChars": "Video Understanding 最大 Chars",
  "tools.media.video.prompt": "Video Understanding 提示",
  "tools.media.video.timeoutSeconds": "Video Understanding 超时 (秒)",
  "tools.media.video.attachments": "Video Understanding 附件 策略",
  "tools.media.video.models": "Video Understanding 模型",
  "tools.media.video.scope": "Video Understanding 范围",
  "tools.links.enabled": "启用 Link Understanding",
  "tools.links.maxLinks": "Link Understanding 最大 Links",
  "tools.links.timeoutSeconds": "Link Understanding 超时 (秒)",
  "tools.links.models": "Link Understanding 模型",
  "tools.links.scope": "Link Understanding 范围",
  "tools.profile": "工具配置文件",
  "tools.alsoAllow": "工具 允许列表 Additions",
  "agents.list[].tools.profile": "代理 工具 配置文件",
  "agents.list[].tools.alsoAllow": "代理 工具 允许列表 Additions",
  "tools.byProvider": "工具 策略 by 提供商",
  "agents.list[].tools.byProvider": "代理 工具 策略 by 提供商",
  "tools.exec.applyPatch.enabled": "启用 apply_patch",
  "tools.exec.applyPatch.workspaceOnly": "apply_patch 仅工作区",
  "tools.exec.applyPatch.allowModels": "apply_patch 模型 允许列表",
  "tools.loopDetection.enabled": "工具 -loop Detection",
  "tools.loopDetection.historySize": "工具 -loop History 大小",
  "tools.loopDetection.warningThreshold": "工具 -loop 警告 阈值",
  "tools.loopDetection.criticalThreshold": "工具 -loop Critical 阈值",
  "tools.loopDetection.globalCircuitBreakerThreshold": "工具 -loop Global Circuit Breaker 阈值",
  "tools.loopDetection.detectors.genericRepeat": "工具 -loop Generic Repeat Detection",
  "tools.loopDetection.detectors.knownPollNoProgress": "工具 -loop Poll No-Progress Detection",
  "tools.loopDetection.detectors.pingPong": "工具 -loop Ping-Pong Detection",
  "tools.fs.workspaceOnly": "仅工作区文件系统工具",
  "tools.sessions.visibility": "会话 工具 可见性",
  "tools.exec.notifyOnExit": "执行 Notify 条件 Exit",
  "tools.exec.notifyOnExitEmptySuccess": "执行 Notify 条件 Empty Success",
  "tools.exec.approvalRunningNoticeMs": "执行 审批 运行中 Notice (ms)",
  "tools.exec.host": "执行主机",
  "tools.exec.security": "执行安全",
  "tools.exec.ask": "执行询问",
  "tools.exec.node": "执行 节点 Binding",
  "tools.agentToAgent": "代理 -to-Agent 工具 访问",
  "tools.agentToAgent.enabled": "启用 代理 -to-Agent 工具",
  "tools.agentToAgent.allow": "代理 -to-Agent 目标 允许列表",
  "tools.elevated": "Elevated 工具 访问",
  "tools.elevated.enabled": "启用 Elevated 工具 访问",
  "tools.elevated.allowFrom": "Elevated 工具 允许 Rules",
  "tools.subagents": "Subagent 工具 策略",
  "tools.subagents.tools": "Subagent 工具 Allow/Deny 策略",
  "tools.sandbox": "沙箱 工具 策略",
  "tools.sandbox.tools": "沙箱 工具 Allow/Deny 策略",
  "tools.exec.pathPrepend": "执行 PATH Prepend",
  "tools.exec.safeBins": "执行 Safe Bins",
  "tools.exec.safeBinTrustedDirs": "执行 Safe Bin Trusted Dirs",
  "tools.exec.safeBinProfiles": "执行 Safe Bin 配置文件",
  approvals: "Approvals",
  "approvals.exec": "执行 审批 Forwarding",
  "approvals.exec.enabled": "转发 执行 审批",
  "approvals.exec.mode": "审批 Forwarding 模式",
  "approvals.exec.agentFilter": "审批 代理 过滤",
  "approvals.exec.sessionFilter": "审批 会话 过滤",
  "approvals.exec.targets": "审批 Forwarding Targets",
  "approvals.exec.targets[].channel": "审批 目标 通道",
  "approvals.exec.targets[].to": "审批 目标 Destination",
  "approvals.exec.targets[].accountId": "审批 目标 账户 ID",
  "approvals.exec.targets[].threadId": "审批 目标 Thread ID",
  "tools.message.allowCrossContextSend": "允许 Cross-Context Messaging",
  "tools.message.crossContext.allowWithinProvider": "允许 Cross-Context (Same Provider)",
  "tools.message.crossContext.allowAcrossProviders": "允许 Cross-Context (Across Providers)",
  "tools.message.crossContext.marker.enabled": "跨上下文标记",
  "tools.message.crossContext.marker.prefix": "Cross-Context Marker 前缀",
  "tools.message.crossContext.marker.suffix": "Cross-Context Marker 后缀",
  "tools.message.broadcast.enabled": "启用 Message Broadcast",
  "tools.web.search.enabled": "启用 网页搜索 工具",
  "tools.web.search.provider": "网页搜索提供商",
  "tools.web.search.apiKey": "Brave 搜索 API 密钥",
  "tools.web.search.maxResults": "网页搜索最大结果数",
  "tools.web.search.timeoutSeconds": "网页搜索 超时 (秒)",
  "tools.web.search.cacheTtlMinutes": "网页搜索 缓存 TTL (分钟)",
  "tools.web.search.brave.mode": "Brave Search Mode",
  "tools.web.search.firecrawl.apiKey": "Firecrawl Search API Key", // pragma: allowlist secret
  "tools.web.search.firecrawl.baseUrl": "Firecrawl Search Base URL",
  "tools.web.search.gemini.apiKey": "Gemini 搜索 API 密钥", // pragma: allowlist secret
  "tools.web.search.gemini.model": "Gemini 搜索 模型",
  "tools.web.search.grok.apiKey": "Grok 搜索 API 密钥", // pragma: allowlist secret
  "tools.web.search.grok.model": "Grok 搜索 模型",
  "tools.web.search.kimi.apiKey": "Kimi 搜索 API 密钥", // pragma: allowlist secret
  "tools.web.search.kimi.baseUrl": "Kimi 搜索 Base URL",
  "tools.web.search.kimi.model": "Kimi 搜索 模型",
  "tools.web.search.perplexity.apiKey": "Perplexity API 密钥", // pragma: allowlist secret
  "tools.web.search.perplexity.baseUrl": "Perplexity 基础 URL",
  "tools.web.search.perplexity.model": "Perplexity 模型",
  "tools.web.fetch.enabled": "启用 Web Fetch 工具",
  "tools.web.fetch.maxChars": "Web Fetch 最大 Chars",
  "tools.web.fetch.maxCharsCap": "Web Fetch Hard 最大 Chars",
  "tools.web.fetch.timeoutSeconds": "Web Fetch 超时 (秒)",
  "tools.web.fetch.cacheTtlMinutes": "Web Fetch 缓存 TTL (分钟)",
  "tools.web.fetch.maxRedirects": "Web Fetch 最大 Redirects",
  "tools.web.fetch.userAgent": "网页获取 User-Agent",
  "tools.web.fetch.readability": "网页获取可读性提取",
  "tools.web.fetch.firecrawl.enabled": "启用 Firecrawl 回退",
  "tools.web.fetch.firecrawl.apiKey": "Firecrawl API 密钥", // pragma: allowlist secret
  "tools.web.fetch.firecrawl.baseUrl": "Firecrawl 基础 URL",
  "tools.web.fetch.firecrawl.onlyMainContent": "Firecrawl Main 内容 Only",
  "tools.web.fetch.firecrawl.maxAgeMs": "Firecrawl 缓存 最大 Age (ms)",
  "tools.web.fetch.firecrawl.timeoutSeconds": "Firecrawl 超时 (秒)",
  "gateway.controlUi.basePath": "控制面板基础路径",
  "gateway.controlUi.root": "控制面板 Assets Root",
  "gateway.controlUi.allowedOrigins": "控制面板允许来源",
  "gateway.controlUi.dangerouslyAllowHostHeaderOriginFallback":
    "Dangerously Allow Host-Header Origin Fallback",
  "gateway.controlUi.allowInsecureAuth": "Insecure 控制面板 Auth Toggle",
  "gateway.controlUi.dangerouslyDisableDeviceAuth": "Dangerously Disable 控制面板 设备 Auth",
  "gateway.push": "Gateway Push Delivery",
  "gateway.push.apns": "Gateway APNs Delivery",
  "gateway.push.apns.relay": "Gateway APNs Relay",
  "gateway.push.apns.relay.baseUrl": "Gateway APNs Relay Base URL",
  "gateway.push.apns.relay.timeoutMs": "Gateway APNs Relay Timeout (ms)",
  "gateway.http.endpoints.chatCompletions.enabled": "OpenAI 聊天补全 端点",
  "gateway.http.endpoints.chatCompletions.maxBodyBytes": "OpenAI 聊天补全 最大 主体 Bytes",
  "gateway.http.endpoints.chatCompletions.maxImageParts": "OpenAI 聊天补全 最大 图片 Parts",
  "gateway.http.endpoints.chatCompletions.maxTotalImageBytes":
    "OpenAI Chat Completions Max Total Image Bytes",
  "gateway.http.endpoints.chatCompletions.images": "OpenAI 聊天补全 图片 限制",
  "gateway.http.endpoints.chatCompletions.images.allowUrl":
    "OpenAI Chat Completions Allow Image URLs",
  "gateway.http.endpoints.chatCompletions.images.urlAllowlist":
    "OpenAI Chat Completions Image URL Allowlist",
  "gateway.http.endpoints.chatCompletions.images.allowedMimes":
    "OpenAI Chat Completions Image MIME Allowlist",
  "gateway.http.endpoints.chatCompletions.images.maxBytes":
    "OpenAI Chat Completions Image Max Bytes",
  "gateway.http.endpoints.chatCompletions.images.maxRedirects":
    "OpenAI Chat Completions Image Max Redirects",
  "gateway.http.endpoints.chatCompletions.images.timeoutMs":
    "OpenAI Chat Completions Image Timeout (ms)",
  "gateway.reload.mode": "配置 重载 模式",
  "gateway.reload.debounceMs": "配置重载防抖 (ms)",
  "gateway.reload.deferralTimeoutMs": "Restart Deferral Timeout (ms)",
  "gateway.nodes.browser.mode": "网关 节点 浏览器 模式",
  "gateway.nodes.browser.node": "网关 节点 浏览器 固定",
  "gateway.nodes.allowCommands": "网关 节点 允许列表 (Extra Commands)",
  "gateway.nodes.denyCommands": "网关 节点 拒绝列表",
  nodeHost: "Node Host",
  "nodeHost.browserProxy": "节点 浏览器 代理",
  "nodeHost.browserProxy.enabled": "节点 浏览器 代理 启用",
  "nodeHost.browserProxy.allowProfiles": "节点 浏览器 代理 允许的 配置文件",
  media: "Media",
  "media.preserveFilenames": "保留 媒体 文件名",
  "media.ttlHours": "媒体 Retention TTL (小时)",
  audio: "Audio",
  "audio.transcription": "音频 Transcription",
  "audio.transcription.command": "音频 Transcription 命令",
  "audio.transcription.timeoutSeconds": "音频 Transcription 超时 (秒)",
  bindings: "Bindings",
  "bindings[].type": "Binding 类型",
  "bindings[].agentId": "Binding 代理 ID",
  "bindings[].match": "绑定匹配规则",
  "bindings[].match.channel": "Binding 通道",
  "bindings[].match.accountId": "Binding 账户 ID",
  "bindings[].match.peer": "绑定对等匹配",
  "bindings[].match.peer.kind": "绑定对等类型",
  "bindings[].match.peer.id": "绑定对等 ID",
  "bindings[].match.guildId": "绑定服务器 ID",
  "bindings[].match.teamId": "绑定团队 ID",
  "bindings[].match.roles": "绑定角色",
  "bindings[].acp": "ACP Binding 覆盖",
  "bindings[].acp.mode": "ACP Binding 模式",
  "bindings[].acp.label": "ACP Binding 标签",
  "bindings[].acp.cwd": "ACP Binding Working 目录",
  "bindings[].acp.backend": "ACP Binding 后端",
  broadcast: "Broadcast",
  "broadcast.strategy": "广播策略",
  "broadcast.*": "Broadcast Destination 列表",
  "skills.load.watch": "Watch 技能",
  "skills.load.watchDebounceMs": "技能 Watch 防抖 (ms)",
  "agents.defaults.workspace": "工作区",
  "agents.defaults.repoRoot": "仓库根目录",
  "agents.defaults.bootstrapMaxChars": "引导消息 最大 Chars",
  "agents.defaults.bootstrapTotalMaxChars": "引导消息 Total 最大 Chars",
  "agents.defaults.bootstrapPromptTruncationWarning": "引导消息 提示 Truncation 警告",
  "agents.defaults.envelopeTimezone": "信封时区",
  "agents.defaults.envelopeTimestamp": "Envelope 时间戳",
  "agents.defaults.envelopeElapsed": "信封已用时间",
  "agents.defaults.memorySearch": "内存 搜索",
  "agents.defaults.memorySearch.enabled": "启用 内存 搜索",
  "agents.defaults.memorySearch.sources": "内存 搜索 Sources",
  "agents.defaults.memorySearch.extraPaths": "Extra 内存 Paths",
  "agents.defaults.memorySearch.multimodal": "内存搜索多模态",
  "agents.defaults.memorySearch.multimodal.enabled": "启用内存搜索多模态",
  "agents.defaults.memorySearch.multimodal.modalities": "内存搜索多模态模式",
  "agents.defaults.memorySearch.multimodal.maxFileBytes": "内存搜索多模态最大文件字节数",
  "agents.defaults.memorySearch.experimental.sessionMemory":
    "Memory Search Session Index (Experimental)",
  "agents.defaults.memorySearch.provider": "内存 搜索 提供商",
  "agents.defaults.memorySearch.remote.baseUrl": "远程嵌入基础 URL",
  "agents.defaults.memorySearch.remote.apiKey": "Remote Embedding API 密钥",
  "agents.defaults.memorySearch.remote.headers": "Remote Embedding 头部",
  "agents.defaults.memorySearch.remote.batch.enabled": "Remote 批次 Embedding 启用",
  "agents.defaults.memorySearch.remote.batch.wait": "Remote 批次 Wait for Completion",
  "agents.defaults.memorySearch.remote.batch.concurrency": "Remote 批次 并发",
  "agents.defaults.memorySearch.remote.batch.pollIntervalMs": "Remote 批次 Poll 间隔 (ms)",
  "agents.defaults.memorySearch.remote.batch.timeoutMinutes": "Remote 批次 超时 (分钟)",
  "agents.defaults.memorySearch.model": "内存 搜索 模型",
  "agents.defaults.memorySearch.outputDimensionality": "内存搜索输出维度",
  "agents.defaults.memorySearch.fallback": "内存 搜索 回退",
  "agents.defaults.memorySearch.local.modelPath": "Local Embedding 模型 路径",
  "agents.defaults.memorySearch.store.path": "内存 搜索 Index 路径",
  "agents.defaults.memorySearch.store.vector.enabled": "内存 搜索 Vector Index",
  "agents.defaults.memorySearch.store.vector.extensionPath": "内存 搜索 Vector 扩展 路径",
  "agents.defaults.memorySearch.chunking.tokens": "内存 Chunk Token",
  "agents.defaults.memorySearch.chunking.overlap": "内存 Chunk Overlap Token",
  "agents.defaults.memorySearch.sync.onSessionStart": "Index on 会话 启动",
  "agents.defaults.memorySearch.sync.onSearch": "Index on 搜索 (Lazy)",
  "agents.defaults.memorySearch.sync.watch": "Watch 内存 Files",
  "agents.defaults.memorySearch.sync.watchDebounceMs": "内存 Watch 防抖 (ms)",
  "agents.defaults.memorySearch.sync.sessions.deltaBytes": "会话 Delta Bytes",
  "agents.defaults.memorySearch.sync.sessions.deltaMessages": "会话 Delta 消息",
  "agents.defaults.memorySearch.sync.sessions.postCompactionForce":
    "Force Reindex After Compaction",
  "agents.defaults.memorySearch.query.maxResults": "内存 搜索 最大 结果",
  "agents.defaults.memorySearch.query.minScore": "内存 搜索 最小 Score",
  "agents.defaults.memorySearch.query.hybrid.enabled": "内存 搜索 Hybrid",
  "agents.defaults.memorySearch.query.hybrid.vectorWeight": "内存 搜索 Vector Weight",
  "agents.defaults.memorySearch.query.hybrid.textWeight": "内存 搜索 文本 Weight",
  "agents.defaults.memorySearch.query.hybrid.candidateMultiplier":
    "Memory Search Hybrid Candidate Multiplier",
  "agents.defaults.memorySearch.query.hybrid.mmr.enabled": "内存 搜索 MMR Re-ranking",
  "agents.defaults.memorySearch.query.hybrid.mmr.lambda": "内存 搜索 MMR Lambda",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.enabled": "内存 搜索 Temporal Decay",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.halfLifeDays":
    "Memory Search Temporal Decay Half-life (Days)",
  "agents.defaults.memorySearch.cache.enabled": "内存 搜索 Embedding 缓存",
  "agents.defaults.memorySearch.cache.maxEntries": "内存 搜索 Embedding 缓存 最大 Entries",
  memory: "Memory",
  "memory.backend": "内存 后端",
  "memory.citations": "内存 Citations 模式",
  "memory.qmd.command": "QMD 二进制文件",
  "memory.qmd.mcporter": "QMD MCPorter",
  "memory.qmd.mcporter.enabled": "QMD MCPorter 启用",
  "memory.qmd.mcporter.serverName": "QMD MCPorter 服务器 名称",
  "memory.qmd.mcporter.startDaemon": "QMD MCPorter 启动 守护进程",
  "memory.qmd.searchMode": "QMD 搜索 模式",
  "memory.qmd.includeDefaultMemory": "QMD Include 默认 内存",
  "memory.qmd.paths": "QMD 额外路径",
  "memory.qmd.paths.path": "QMD 路径",
  "memory.qmd.paths.pattern": "QMD 路径 模式",
  "memory.qmd.paths.name": "QMD 路径 名称",
  "memory.qmd.sessions.enabled": "QMD 会话 Indexing",
  "memory.qmd.sessions.exportDir": "QMD 会话 导出 目录",
  "memory.qmd.sessions.retentionDays": "QMD 会话 Retention (days)",
  "memory.qmd.update.interval": "QMD 更新 间隔",
  "memory.qmd.update.debounceMs": "QMD 更新 防抖 (ms)",
  "memory.qmd.update.onBoot": "QMD 更新 on Startup",
  "memory.qmd.update.waitForBootSync": "QMD 等待启动同步",
  "memory.qmd.update.embedInterval": "QMD Embed 间隔",
  "memory.qmd.update.commandTimeoutMs": "QMD 命令 超时 (ms)",
  "memory.qmd.update.updateTimeoutMs": "QMD 更新 超时 (ms)",
  "memory.qmd.update.embedTimeoutMs": "QMD Embed 超时 (ms)",
  "memory.qmd.limits.maxResults": "QMD 最大 结果",
  "memory.qmd.limits.maxSnippetChars": "QMD 最大 Snippet Chars",
  "memory.qmd.limits.maxInjectedChars": "QMD 最大 Injected Chars",
  "memory.qmd.limits.timeoutMs": "QMD 搜索 超时 (ms)",
  "memory.qmd.scope": "QMD Surface 范围",
  auth: "Auth",
  "auth.profiles": "Auth 配置文件",
  "auth.order": "Auth 配置文件 Order",
  "auth.cooldowns": "认证冷却",
  acp: "ACP",
  "acp.enabled": "ACP 启用",
  "acp.dispatch.enabled": "ACP 调度 启用",
  "acp.backend": "ACP 后端",
  "acp.defaultAgent": "ACP 默认代理",
  "acp.allowedAgents": "ACP 允许的代理",
  "acp.maxConcurrentSessions": "ACP 最大并发会话",
  "acp.stream": "ACP 流",
  "acp.stream.coalesceIdleMs": "ACP 流 Coalesce 空闲 (ms)",
  "acp.stream.maxChunkChars": "ACP 流 最大 Chunk Chars",
  "acp.stream.repeatSuppression": "ACP 流 Repeat Suppression",
  "acp.stream.deliveryMode": "ACP 流 Delivery 模式",
  "acp.stream.hiddenBoundarySeparator": "ACP 流 Hidden Boundary Separator",
  "acp.stream.maxOutputChars": "ACP 流 最大 输出 Chars",
  "acp.stream.maxSessionUpdateChars": "ACP 流 最大 会话 更新 Chars",
  "acp.stream.tagVisibility": "ACP 流 标签 可见性",
  "acp.runtime.ttlMinutes": "ACP 运行时 TTL (minutes)",
  "acp.runtime.installCommand": "ACP 运行时 Install 命令",
  models: "Models",
  "models.mode": "模型 Catalog 模式",
  "models.providers": "模型 提供商",
  "models.providers.*.baseUrl": "模型 提供商 Base URL",
  "models.providers.*.apiKey": "模型 提供商 API 密钥", // pragma: allowlist secret
  "models.providers.*.auth": "模型 提供商 Auth 模式",
  "models.providers.*.api": "模型 提供商 API Adapter",
  "models.providers.*.injectNumCtxForOpenAICompat": "模型 提供商 Inject num_ctx (OpenAI Compat)",
  "models.providers.*.headers": "模型 提供商 头部",
  "models.providers.*.authHeader": "模型 提供商 Authorization Header",
  "models.providers.*.models": "模型 提供商 模型 列表",
  "models.bedrockDiscovery": "Bedrock 模型 发现",
  "models.bedrockDiscovery.enabled": "Bedrock 发现 启用",
  "models.bedrockDiscovery.region": "Bedrock 发现 Region",
  "models.bedrockDiscovery.providerFilter": "Bedrock 发现 提供商 过滤",
  "models.bedrockDiscovery.refreshInterval": "Bedrock 发现 刷新 间隔 (秒)",
  "models.bedrockDiscovery.defaultContextWindow": "Bedrock 默认 上下文 窗口",
  "models.bedrockDiscovery.defaultMaxTokens": "Bedrock 默认 最大 Token",
  "auth.cooldowns.billingBackoffHours": "Billing 退避 (小时)",
  "auth.cooldowns.billingBackoffHoursByProvider": "Billing 退避 覆盖",
  "auth.cooldowns.billingMaxHours": "Billing 退避 Cap (小时)",
  "auth.cooldowns.failureWindowHours": "Failover 窗口 (小时)",
  "agents.defaults.models": "模型",
  "agents.defaults.model.primary": "主要 模型",
  "agents.defaults.model.fallbacks": "模型回退 s",
  "agents.defaults.imageModel.primary": "图片 模型",
  "agents.defaults.imageModel.fallbacks": "图片 模型回退 s",
  "agents.defaults.pdfModel.primary": "PDF 模型",
  "agents.defaults.pdfModel.fallbacks": "PDF 模型回退 s",
  "agents.defaults.pdfMaxBytesMb": "PDF 最大 大小 (MB)",
  "agents.defaults.pdfMaxPages": "PDF 最大 Pages",
  "agents.defaults.imageMaxDimensionPx": "图片 最大 Dimension (px)",
  "agents.defaults.humanDelay.mode": "Human 延迟 模式",
  "agents.defaults.humanDelay.minMs": "Human 延迟 最小 (ms)",
  "agents.defaults.humanDelay.maxMs": "Human 延迟 最大 (ms)",
  "agents.defaults.cliBackends": "CLI 后端",
  "agents.defaults.compaction": "压缩",
  "agents.defaults.compaction.mode": "压缩 模式",
  "agents.defaults.compaction.reserveTokens": "压缩 Reserve Token",
  "agents.defaults.compaction.keepRecentTokens": "压缩 Keep Recent Token",
  "agents.defaults.compaction.reserveTokensFloor": "压缩 Reserve 令牌 Floor",
  "agents.defaults.compaction.maxHistoryShare": "压缩 最大 History Share",
  "agents.defaults.compaction.identifierPolicy": "压缩 标识符 策略",
  "agents.defaults.compaction.identifierInstructions": "压缩 标识符 指令",
  "agents.defaults.compaction.recentTurnsPreserve": "压缩 保留 Recent 轮数",
  "agents.defaults.compaction.qualityGuard": "压缩 Quality Guard",
  "agents.defaults.compaction.qualityGuard.enabled": "压缩 Quality Guard 启用",
  "agents.defaults.compaction.qualityGuard.maxRetries": "压缩 Quality Guard 最大 重试",
  "agents.defaults.compaction.postIndexSync": "Compaction Post-Index Sync",
  "agents.defaults.compaction.postCompactionSections": "Post-Compaction 上下文 Sections",
  "agents.defaults.compaction.timeoutSeconds": "Compaction Timeout (Seconds)",
  "agents.defaults.compaction.model": "Compaction Model Override",
  "agents.defaults.compaction.memoryFlush": "压缩 内存 刷新",
  "agents.defaults.compaction.memoryFlush.enabled": "压缩 内存 刷新 启用",
  "agents.defaults.compaction.memoryFlush.softThresholdTokens":
    "Compaction Memory Flush Soft Threshold",
  "agents.defaults.compaction.memoryFlush.forceFlushTranscriptBytes":
    "Compaction Memory Flush Transcript Size Threshold",
  "agents.defaults.compaction.memoryFlush.prompt": "压缩 内存 刷新 提示",
  "agents.defaults.compaction.memoryFlush.systemPrompt": "压缩 内存 刷新 系统 提示",
  "agents.defaults.embeddedPi": "嵌入式 Pi",
  "agents.defaults.embeddedPi.projectSettingsPolicy": "Embedded Pi Project 设置 策略",
  "agents.defaults.heartbeat.directPolicy": "心跳 Direct 策略",
  "agents.list.*.heartbeat.directPolicy": "心跳 Direct 策略",
  "agents.defaults.heartbeat.suppressToolErrorWarnings": "心跳 Suppress 工具 错误 Warnings",
  "agents.defaults.sandbox.browser.network": "沙箱 浏览器 网络",
  "agents.defaults.sandbox.browser.cdpSourceRange": "沙箱 浏览器 CDP 来源 端口 范围",
  "agents.defaults.sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "Sandbox Docker Allow Container Namespace Join",
  commands: "Commands",
  "commands.native": "Native 命令",
  "commands.nativeSkills": "Native 技能 命令",
  "commands.text": "文本 命令",
  "commands.bash": "允许 Bash Chat 命令",
  "commands.bashForegroundMs": "Bash Foreground 窗口 (ms)",
  "commands.config": "允许 /config",
  "commands.debug": "允许 /debug",
  "commands.restart": "允许 重启",
  "commands.useAccessGroups": "Use 访问 Groups",
  "commands.ownerAllowFrom": "命令 Owners",
  "commands.ownerDisplay": "所有者 ID 显示",
  "commands.ownerDisplaySecret": "Owner ID Hash 密钥", // pragma: allowlist secret
  "commands.allowFrom": "命令 Elevated 访问 Rules",
  ui: "UI",
  "ui.seamColor": "强调 颜色",
  "ui.assistant": "助手外观",
  "ui.assistant.name": "Assistant 名称",
  "ui.assistant.avatar": "Assistant 头像",
  "browser.evaluateEnabled": "浏览器 Evaluate 启用",
  "browser.snapshotDefaults": "浏览器 Snapshot 默认设置",
  "browser.snapshotDefaults.mode": "浏览器 Snapshot 模式",
  "browser.ssrfPolicy": "浏览器 SSRF 策略",
  "browser.ssrfPolicy.allowPrivateNetwork": "浏览器 允许 Private 网络",
  "browser.ssrfPolicy.dangerouslyAllowPrivateNetwork": "浏览器 Dangerously 允许 Private 网络",
  "browser.ssrfPolicy.allowedHostnames": "浏览器 允许的 Hostnames",
  "browser.ssrfPolicy.hostnameAllowlist": "浏览器 Hostname 允许列表",
  "browser.remoteCdpTimeoutMs": "Remote CDP 超时 (ms)",
  "browser.remoteCdpHandshakeTimeoutMs": "Remote CDP Handshake 超时 (ms)",
  session: "Session",
  "session.scope": "会话 范围",
  "session.dmScope": "DM 会话 范围",
  "session.identityLinks": "会话 身份 Links",
  "session.resetTriggers": "会话 重置 Triggers",
  "session.idleMinutes": "会话 空闲 Minutes",
  "session.reset": "会话 重置 策略",
  "session.reset.mode": "会话 重置 模式",
  "session.reset.atHour": "会话 Daily 重置 Hour",
  "session.reset.idleMinutes": "会话 重置 空闲 Minutes",
  "session.resetByType": "会话 重置 by Chat 类型",
  "session.resetByType.direct": "会话 重置 (Direct)",
  "session.resetByType.dm": "会话 重置 (DM Deprecated Alias)",
  "session.resetByType.group": "会话 重置 (Group)",
  "session.resetByType.thread": "会话 重置 (Thread)",
  "session.resetByChannel": "会话 重置 by 通道",
  "session.store": "会话 存储 路径",
  "session.typingIntervalSeconds": "会话 Typing 间隔 (seconds)",
  "session.typingMode": "会话 Typing 模式",
  "session.parentForkMaxTokens": "会话 Parent Fork 最大 Token",
  "session.mainKey": "会话 Main 密钥",
  "session.sendPolicy": "会话 Send 策略",
  "session.sendPolicy.default": "会话 Send 策略 默认 操作",
  "session.sendPolicy.rules": "会话 Send 策略 Rules",
  "session.sendPolicy.rules[].action": "会话 Send Rule 操作",
  "session.sendPolicy.rules[].match": "会话 Send Rule Match",
  "session.sendPolicy.rules[].match.channel": "会话 Send Rule 通道",
  "session.sendPolicy.rules[].match.chatType": "会话 Send Rule Chat 类型",
  "session.sendPolicy.rules[].match.keyPrefix": "会话 Send Rule 密钥 前缀",
  "session.sendPolicy.rules[].match.rawKeyPrefix": "会话 Send Rule Raw 密钥 前缀",
  "session.agentToAgent": "会话 代理 -to-Agent",
  "session.agentToAgent.maxPingPongTurns": "代理 -to-Agent Ping-Pong 轮数",
  "session.threadBindings": "会话 线程绑定",
  "session.threadBindings.enabled": "线程绑定 启用",
  "session.threadBindings.idleHours": "线程绑定 空闲 超时 (小时)",
  "session.threadBindings.maxAgeHours": "线程绑定 最大 Age (小时)",
  "session.maintenance": "会话 Maintenance",
  "session.maintenance.mode": "会话 Maintenance 模式",
  "session.maintenance.pruneAfter": "会话 Prune After",
  "session.maintenance.pruneDays": "会话 Prune Days (Deprecated)",
  "session.maintenance.maxEntries": "会话 最大 Entries",
  "session.maintenance.rotateBytes": "会话 Rotate 大小",
  "session.maintenance.resetArchiveRetention": "会话 重置 归档 Retention",
  "session.maintenance.maxDiskBytes": "会话 最大 Disk 预算",
  "session.maintenance.highWaterBytes": "会话 Disk High-water 目标",
  cron: "Cron",
  "cron.enabled": "定时任务启用",
  "cron.store": "定时任务 存储 路径",
  "cron.maxConcurrentRuns": "定时任务 最大 并发 Runs",
  "cron.retry": "定时任务 重试 策略",
  "cron.retry.maxAttempts": "定时任务 重试 最大 尝试次数",
  "cron.retry.backoffMs": "定时任务 重试 退避 (ms)",
  "cron.retry.retryOn": "定时任务 重试 错误 Types",
  "cron.webhook": "定时任务 Legacy Webhook (Deprecated)",
  "cron.webhookToken": "定时任务 Webhook Bearer 令牌",
  "cron.sessionRetention": "定时任务 会话 Retention",
  "cron.runLog": "定时任务 运行 日志 Pruning",
  "cron.runLog.maxBytes": "定时任务 运行 日志 最大 Bytes",
  "cron.runLog.keepLines": "定时任务 运行 日志 Keep Lines",
  hooks: "Hooks",
  "hooks.enabled": "钩子启用",
  "hooks.path": "钩子 端点 路径",
  "hooks.token": "钩子 Auth 令牌",
  "hooks.defaultSessionKey": "钩子 默认 会话 密钥",
  "hooks.allowRequestSessionKey": "钩子 允许 请求 会话 密钥",
  "hooks.allowedSessionKeyPrefixes": "钩子 允许的 会话 密钥 Prefixes",
  "hooks.allowedAgentIds": "钩子 允许的 代理 IDs",
  "hooks.maxBodyBytes": "钩子 最大 主体 Bytes",
  "hooks.presets": "钩子 Presets",
  "hooks.transformsDir": "钩子 Transforms 目录",
  "hooks.mappings": "钩子 Mappings",
  "hooks.mappings[].id": "钩子 Mapping ID",
  "hooks.mappings[].match": "钩子 Mapping Match",
  "hooks.mappings[].match.path": "钩子 Mapping Match 路径",
  "hooks.mappings[].match.source": "钩子 Mapping Match 来源",
  "hooks.mappings[].action": "钩子 Mapping 操作",
  "hooks.mappings[].wakeMode": "钩子 Mapping Wake 模式",
  "hooks.mappings[].name": "钩子 Mapping 名称",
  "hooks.mappings[].agentId": "钩子 Mapping 代理 ID",
  "hooks.mappings[].sessionKey": "钩子 Mapping 会话 密钥",
  "hooks.mappings[].messageTemplate": "钩子 Mapping Message 模板",
  "hooks.mappings[].textTemplate": "钩子 Mapping 文本 模板",
  "hooks.mappings[].deliver": "钩子 Mapping Deliver 回复",
  "hooks.mappings[].allowUnsafeExternalContent": "钩子 Mapping 允许 Unsafe External 内容",
  "hooks.mappings[].channel": "钩子 Mapping Delivery 通道",
  "hooks.mappings[].to": "钩子 Mapping Delivery Destination",
  "hooks.mappings[].model": "钩子 Mapping 模型 覆盖",
  "hooks.mappings[].thinking": "钩子 Mapping 思考 覆盖",
  "hooks.mappings[].timeoutSeconds": "钩子 Mapping 超时 (秒)",
  "hooks.mappings[].transform": "钩子 Mapping Transform",
  "hooks.mappings[].transform.module": "钩子 Transform Module",
  "hooks.mappings[].transform.export": "钩子 Transform 导出",
  "hooks.gmail": "Gmail 钩子",
  "hooks.gmail.account": "Gmail 钩子 账户",
  "hooks.gmail.label": "Gmail 钩子 标签",
  "hooks.gmail.topic": "Gmail 钩子 Pub/Sub Topic",
  "hooks.gmail.subscription": "Gmail 钩子 Subscription",
  "hooks.gmail.pushToken": "Gmail 钩子 Push 令牌",
  "hooks.gmail.hookUrl": "Gmail 钩子 Callback URL",
  "hooks.gmail.includeBody": "Gmail 钩子 Include 主体",
  "hooks.gmail.maxBytes": "Gmail 钩子 最大 主体 Bytes",
  "hooks.gmail.renewEveryMinutes": "Gmail 钩子 Renew 间隔 (分钟)",
  "hooks.gmail.allowUnsafeExternalContent": "Gmail 钩子 允许 Unsafe External 内容",
  "hooks.gmail.serve": "Gmail 钩子 Local 服务器",
  "hooks.gmail.serve.bind": "Gmail 钩子 服务器 绑定 Address",
  "hooks.gmail.serve.port": "Gmail 钩子 服务器 端口",
  "hooks.gmail.serve.path": "Gmail 钩子 服务器 路径",
  "hooks.gmail.tailscale": "Gmail 钩子 Tailscale",
  "hooks.gmail.tailscale.mode": "Gmail 钩子 Tailscale 模式",
  "hooks.gmail.tailscale.path": "Gmail 钩子 Tailscale 路径",
  "hooks.gmail.tailscale.target": "Gmail 钩子 Tailscale 目标",
  "hooks.gmail.model": "Gmail 钩子 模型 覆盖",
  "hooks.gmail.thinking": "Gmail 钩子 思考 覆盖",
  "hooks.internal": "Internal 钩子",
  "hooks.internal.enabled": "Internal 钩子 启用",
  "hooks.internal.handlers": "Internal 钩子 Handlers",
  "hooks.internal.handlers[].event": "Internal 钩子 事件",
  "hooks.internal.handlers[].module": "Internal 钩子 Module",
  "hooks.internal.handlers[].export": "Internal 钩子 导出",
  "hooks.internal.entries": "Internal 钩子 Entries",
  "hooks.internal.load": "Internal 钩子 Loader",
  "hooks.internal.load.extraDirs": "Internal 钩子 Extra Directories",
  "hooks.internal.installs": "Internal 钩子 Install Records",
  web: "Web Channel",
  "web.enabled": "Web 通道 启用",
  "web.heartbeatSeconds": "Web 通道 心跳 间隔 (秒)",
  "web.reconnect": "Web 通道 Reconnect 策略",
  "web.reconnect.initialMs": "Web Reconnect Initial 延迟 (ms)",
  "web.reconnect.maxMs": "Web Reconnect 最大 延迟 (ms)",
  "web.reconnect.factor": "Web Reconnect 退避 Factor",
  "web.reconnect.jitter": "Web Reconnect 抖动",
  "web.reconnect.maxAttempts": "Web Reconnect 最大 尝试次数",
  discovery: "Discovery",
  "discovery.wideArea": "Wide-area 发现",
  "discovery.wideArea.enabled": "Wide-area 发现 启用",
  "discovery.wideArea.domain": "Wide-area 发现 域名",
  "discovery.mdns": "mDNS 发现",
  canvasHost: "Canvas Host",
  "canvasHost.enabled": "Canvas 主机 启用",
  "canvasHost.root": "Canvas 主机 Root 目录",
  "canvasHost.port": "Canvas 主机 端口",
  "canvasHost.liveReload": "Canvas 主机 Live 重载",
  talk: "Talk",
  "talk.voiceId": "语音 语音 ID",
  "talk.voiceAliases": "语音 语音 Aliases",
  "talk.modelId": "语音 模型 ID",
  "talk.outputFormat": "语音 输出 格式",
  "talk.interruptOnSpeech": "语音 Interrupt on 语音",
  "talk.silenceTimeoutMs": "Talk Silence Timeout (ms)",
  messages: "Messages",
  "messages.messagePrefix": "Inbound Message 前缀",
  "messages.responsePrefix": "Outbound 响应前缀",
  "messages.groupChat": "群聊规则",
  "messages.groupChat.mentionPatterns": "Group 提及 模式",
  "messages.groupChat.historyLimit": "Group History 限制",
  "messages.queue": "Inbound 队列",
  "messages.queue.mode": "队列 模式",
  "messages.queue.byChannel": "队列 模式 by 通道",
  "messages.queue.debounceMs": "队列 防抖 (ms)",
  "messages.queue.debounceMsByChannel": "队列 防抖 by 通道 (ms)",
  "messages.queue.cap": "队列 Capacity",
  "messages.queue.drop": "队列 Drop Strategy",
  "messages.inbound": "Inbound 防抖",
  "messages.suppressToolErrors": "Suppress 工具 错误 Warnings",
  "messages.ackReaction": "确认反应 表情",
  "messages.ackReactionScope": "确认反应 范围",
  "messages.removeAckAfterReply": "移除 确认反应 After 回复",
  "messages.statusReactions": "状态 Reactions",
  "messages.statusReactions.enabled": "启用 状态 Reactions",
  "messages.statusReactions.emojis": "状态 反应 Emojis",
  "messages.statusReactions.timing": "状态 反应 Timing",
  "messages.inbound.debounceMs": "Inbound Message 防抖 (ms)",
  "messages.inbound.byChannel": "Inbound 防抖 by 通道 (ms)",
  "messages.tts": "消息文字转语音",
  "talk.provider": "语音 Active 提供商",
  "talk.providers": "语音 提供商 设置",
  "talk.providers.*.voiceId": "语音 提供商 语音 ID",
  "talk.providers.*.voiceAliases": "语音 提供商 语音 Aliases",
  "talk.providers.*.modelId": "语音 提供商 模型 ID",
  "talk.providers.*.outputFormat": "语音 提供商 输出 格式",
  "talk.providers.*.apiKey": "语音 提供商 API 密钥", // pragma: allowlist secret
  "talk.apiKey": "语音 API 密钥", // pragma: allowlist secret
  channels: "Channels",
  "channels.defaults": "通道 默认设置",
  "channels.defaults.groupPolicy": "默认 Group 策略",
  "channels.defaults.heartbeat": "默认 心跳 可见性",
  "channels.defaults.heartbeat.showOk": "心跳 Show OK",
  "channels.defaults.heartbeat.showAlerts": "心跳 Show Alerts",
  "channels.defaults.heartbeat.useIndicator": "心跳 Use Indicator",
  "channels.whatsapp": "WhatsApp",
  "channels.telegram": "Telegram",
  "channels.telegram.customCommands": "Telegram 自定义 命令",
  "channels.discord": "Discord",
  "channels.slack": "Slack",
  "channels.mattermost": "Mattermost",
  "channels.signal": "Signal",
  "channels.imessage": "iMessage",
  "channels.bluebubbles": "BlueBubbles",
  "channels.msteams": "MS Teams",
  "channels.modelByChannel": "通道 模型 覆盖",
  ...IRC_FIELD_LABELS,
  "channels.telegram.botToken": "Telegram Bot 令牌",
  "channels.telegram.dmPolicy": "Telegram 私信策略",
  "channels.telegram.configWrites": "Telegram 配置 Writes",
  "channels.telegram.commands.native": "Telegram Native 命令",
  "channels.telegram.commands.nativeSkills": "Telegram Native 技能 命令",
  "channels.telegram.streaming": "Telegram Streaming 模式",
  "channels.telegram.retry.attempts": "Telegram 重试 尝试次数",
  "channels.telegram.retry.minDelayMs": "Telegram 重试 最小 延迟 (ms)",
  "channels.telegram.retry.maxDelayMs": "Telegram 重试 最大 延迟 (ms)",
  "channels.telegram.retry.jitter": "Telegram 重试 抖动",
  "channels.telegram.network.autoSelectFamily": "Telegram 自动选择协议族",
  "channels.telegram.timeoutSeconds": "Telegram API 超时 (seconds)",
  "channels.telegram.capabilities.inlineButtons": "Telegram 内联按钮",
  "channels.telegram.execApprovals": "Telegram 执行审批",
  "channels.telegram.execApprovals.enabled": "Telegram 执行审批启用",
  "channels.telegram.execApprovals.approvers": "Telegram 执行审批审批人",
  "channels.telegram.execApprovals.agentFilter": "Telegram 执行审批代理过滤",
  "channels.telegram.execApprovals.sessionFilter": "Telegram 执行审批会话过滤",
  "channels.telegram.execApprovals.target": "Telegram 执行审批目标",
  "channels.telegram.threadBindings.enabled": "Telegram 线程绑定 启用",
  "channels.telegram.threadBindings.idleHours": "Telegram 线程绑定 空闲 超时 (小时)",
  "channels.telegram.threadBindings.maxAgeHours": "Telegram 线程绑定 最大 Age (小时)",
  "channels.telegram.threadBindings.spawnSubagentSessions": "Telegram 线程绑定子代理生成",
  "channels.telegram.threadBindings.spawnAcpSessions": "Telegram 线程绑定 ACP 生成",
  "channels.whatsapp.dmPolicy": "WhatsApp 私信策略",
  "channels.whatsapp.selfChatMode": "WhatsApp Self-Phone 模式",
  "channels.whatsapp.debounceMs": "WhatsApp Message 防抖 (ms)",
  "channels.whatsapp.configWrites": "WhatsApp 配置 Writes",
  "channels.signal.dmPolicy": "Signal 私信策略",
  "channels.signal.configWrites": "Signal 配置 Writes",
  "channels.imessage.dmPolicy": "iMessage 私信策略",
  "channels.imessage.configWrites": "iMessage 配置 Writes",
  "channels.bluebubbles.dmPolicy": "BlueBubbles 私信策略",
  "channels.msteams.configWrites": "MS Teams 配置 Writes",
  "channels.irc.configWrites": "IRC 配置 Writes",
  "channels.discord.dmPolicy": "Discord 私信策略",
  "channels.discord.dm.policy": "Discord 私信策略",
  "channels.discord.configWrites": "Discord 配置 Writes",
  "channels.discord.proxy": "Discord 代理 URL",
  "channels.discord.commands.native": "Discord Native 命令",
  "channels.discord.commands.nativeSkills": "Discord Native 技能 命令",
  "channels.discord.streaming": "Discord Streaming 模式",
  "channels.discord.streamMode": "Discord 流 模式 (Legacy)",
  "channels.discord.draftChunk.minChars": "Discord Draft Chunk 最小 Chars",
  "channels.discord.draftChunk.maxChars": "Discord Draft Chunk 最大 Chars",
  "channels.discord.draftChunk.breakPreference": "Discord 草稿分块断行偏好",
  "channels.discord.retry.attempts": "Discord 重试 尝试次数",
  "channels.discord.retry.minDelayMs": "Discord 重试 最小 延迟 (ms)",
  "channels.discord.retry.maxDelayMs": "Discord 重试 最大 延迟 (ms)",
  "channels.discord.retry.jitter": "Discord 重试 抖动",
  "channels.discord.maxLinesPerMessage": "Discord 最大 Lines Per Message",
  "channels.discord.inboundWorker.runTimeoutMs": "Discord 入站工作者 超时 (ms)",
  "channels.discord.eventQueue.listenerTimeout": "Discord EventQueue 监听器 超时 (ms)",
  "channels.discord.eventQueue.maxQueueSize": "Discord EventQueue 最大 队列 大小",
  "channels.discord.eventQueue.maxConcurrency": "Discord EventQueue 最大 并发",
  "channels.discord.threadBindings.enabled": "Discord 线程绑定 启用",
  "channels.discord.threadBindings.idleHours": "Discord 线程绑定 空闲 超时 (小时)",
  "channels.discord.threadBindings.maxAgeHours": "Discord 线程绑定 最大 Age (小时)",
  "channels.discord.threadBindings.spawnSubagentSessions": "Discord 线程绑定子代理生成",
  "channels.discord.threadBindings.spawnAcpSessions": "Discord 线程绑定 ACP 生成",
  "channels.discord.ui.components.accentColor": "Discord Component 强调 颜色",
  "channels.discord.intents.presence": "Discord 存在状态 Intent",
  "channels.discord.intents.guildMembers": "Discord 服务器成员意图",
  "channels.discord.voice.enabled": "Discord 语音 启用",
  "channels.discord.voice.autoJoin": "Discord 语音 Auto-Join",
  "channels.discord.voice.daveEncryption": "Discord 语音 DAVE 加密",
  "channels.discord.voice.decryptionFailureTolerance": "Discord 语音 Decrypt Failure Tolerance",
  "channels.discord.voice.tts": "Discord 语音 Text-to-Speech",
  "channels.discord.pluralkit.enabled": "Discord PluralKit 启用",
  "channels.discord.pluralkit.token": "Discord PluralKit 令牌",
  "channels.discord.activity": "Discord 存在状态 活动",
  "channels.discord.status": "Discord 存在状态 状态",
  "channels.discord.autoPresence.enabled": "Discord 自动状态启用",
  "channels.discord.autoPresence.intervalMs": "Discord 自动状态 检查 间隔 (ms)",
  "channels.discord.autoPresence.minUpdateIntervalMs":
    "Discord Auto Presence Min Update Interval (ms)",
  "channels.discord.autoPresence.healthyText": "Discord 自动状态 Healthy 文本",
  "channels.discord.autoPresence.degradedText": "Discord 自动状态 Degraded 文本",
  "channels.discord.autoPresence.exhaustedText": "Discord 自动状态 Exhausted 文本",
  "channels.discord.activityType": "Discord 存在状态 活动 类型",
  "channels.discord.activityUrl": "Discord 存在状态 活动 URL",
  "channels.slack.dm.policy": "Slack 私信策略",
  "channels.slack.dmPolicy": "Slack 私信策略",
  "channels.slack.configWrites": "Slack 配置 Writes",
  "channels.slack.commands.native": "Slack Native 命令",
  "channels.slack.commands.nativeSkills": "Slack Native 技能 命令",
  "channels.slack.allowBots": "Slack 允许 Bot 消息",
  "channels.discord.allowBots": "Discord 允许 Bot 消息",
  "channels.discord.token": "Discord Bot 令牌",
  "channels.slack.botToken": "Slack 机器人令牌",
  "channels.slack.appToken": "Slack 应用令牌",
  "channels.slack.userToken": "Slack 用户 令牌",
  "channels.slack.userTokenReadOnly": "Slack 用户 令牌 已读 Only",
  "channels.slack.capabilities.interactiveReplies": "Slack 交互式回复",
  "channels.slack.streaming": "Slack Streaming 模式",
  "channels.slack.nativeStreaming": "Slack 原生流式传输",
  "channels.slack.streamMode": "Slack 流 模式 (Legacy)",
  "channels.slack.thread.historyScope": "Slack Thread History 范围",
  "channels.slack.thread.inheritParent": "Slack 线程父级继承",
  "channels.slack.thread.initialHistoryLimit": "Slack Thread Initial History 限制",
  "channels.mattermost.botToken": "Mattermost Bot 令牌",
  "channels.mattermost.baseUrl": "Mattermost 基础 URL",
  "channels.mattermost.configWrites": "Mattermost 配置 Writes",
  "channels.mattermost.chatmode": "Mattermost Chat 模式",
  "channels.mattermost.oncharPrefixes": "Mattermost Onchar 前缀",
  "channels.mattermost.requireMention": "Mattermost 需要 提及",
  "channels.signal.account": "Signal 账户",
  "channels.imessage.cliPath": "iMessage CLI 路径",
  "agents.list[].skills": "代理技能过滤",
  "agents.list[].identity.avatar": "代理 头像",
  "agents.list[].heartbeat.suppressToolErrorWarnings":
    "Agent Heartbeat Suppress Tool Error Warnings",
  "agents.list[].sandbox.browser.network": "代理 沙箱 浏览器 网络",
  "agents.list[].sandbox.browser.cdpSourceRange": "代理 沙箱 浏览器 CDP 来源 端口 范围",
  "agents.list[].sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "Agent Sandbox Docker Allow Container Namespace Join",
  "discovery.mdns.mode": "mDNS 发现 模式",
  plugins: "Plugins",
  "plugins.enabled": "启用 插件",
  "plugins.allow": "插件 允许列表",
  "plugins.deny": "插件 拒绝列表",
  "plugins.load": "插件 Loader",
  "plugins.load.paths": "插件 加载 Paths",
  "plugins.slots": "插件 槽位",
  "plugins.slots.memory": "内存 插件",
  "plugins.slots.contextEngine": "上下文 引擎 插件",
  "plugins.entries": "插件 Entries",
  "plugins.entries.*.enabled": "插件 启用",
  "plugins.entries.*.hooks": "插件 钩子 策略",
  "plugins.entries.*.hooks.allowPromptInjection": "允许 提示 注入 钩子",
  "plugins.entries.*.apiKey": "插件 API 密钥", // pragma: allowlist secret
  "plugins.entries.*.env": "插件 Environment 变量",
  "plugins.entries.*.config": "插件 配置",
  "plugins.installs": "插件 Install Records",
  "plugins.installs.*.source": "插件 Install 来源",
  "plugins.installs.*.spec": "插件 Install Spec",
  "plugins.installs.*.sourcePath": "插件 Install 来源 路径",
  "plugins.installs.*.installPath": "插件 Install 路径",
  "plugins.installs.*.version": "插件 Install 版本",
  "plugins.installs.*.resolvedName": "插件 Resolved Package 名称",
  "plugins.installs.*.resolvedVersion": "插件 Resolved Package 版本",
  "plugins.installs.*.resolvedSpec": "插件 Resolved Package Spec",
  "plugins.installs.*.integrity": "插件 Resolved Integrity",
  "plugins.installs.*.shasum": "插件 Resolved Shasum",
  "plugins.installs.*.resolvedAt": "插件 Resolution Time",
  "plugins.installs.*.installedAt": "插件 Install Time",
  "plugins.installs.*.marketplaceName": "Plugin Marketplace Name",
  "plugins.installs.*.marketplaceSource": "Plugin Marketplace Source",
  "plugins.installs.*.marketplacePlugin": "Plugin Marketplace Plugin",
};
